### ISSUE TITLE
Silent token refresh for MSA

### ISSUE THREAD

**Issue by cdmayer** [OneDrive/onedrive-sdk-dotnet-msa-auth-adapter#7]

**Comment by tweant** [comment]
As I've asked on Stackoverflow http://stackoverflow.com/questions/39035054/c-sharp-onedrive-auto-login-after-initial-authorisation about silently login user after first authorization it seems that in v 2.0.0 there are not implemented methods such as `GetSilentlyAuthenticatedMicrosoftAccountClient` on `OneDriveClient`.

**Comment by tipa** [comment]
I need an option to connect to OneDrive only when it can be done silently (without prompting the user). So if the user did not authorize the app before, `AuthenticateUserAsync()` should just fail. Is this what this issue is about? If yes, is there a possible workaround?

**Comment by cdmayer** [comment]
Fixed in #11.

**Comment by cdmayer** [comment]
Check out 1.0.4 in Nuget.

**Comment by anyto** [comment]
Hi. Czy he would can Ktoś in figure complete demonstration html or present video exactly step after step how fill all field in project https:// github.com / OneDrive / onedrive - sample - apibrowser-dotnet 

the best to concretely on example names or to show in code the chains of signs this project 
for C # because I have problem what data with possessed account in Microsoft to take and then where to write in which place nalezy in code it 

this enough inexplicable for me is how also the description lack of this project how oneself the Studio will start him in Visual what all elements mark to what serve in Menu of project beginning from Menu: File...

concretely after entry to Menu nothing wants me MSA File to load how I understand this the side of log in to account Microsoft she should show already from my correct data written automatically in this window...

How do to execute this to this project for me wszytskie these field filled because this side does not want to show even to log in to account Microsoft ?!!! even if empty to I would can fill this by hand...

nothing appears such me and therefore I ask show me how to write this nalezy in code this project correctly what value and I with what location from my account Microsoft have these values to gain over...

thanks Anyto
